Picking_Web/Controllers/API/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using Picking_Web.Models;
using AutoMapper;
using Picking_Web.DTOs;
using Picking_Web.Helpers;
using Microsoft.AspNet.Identity;

namespace Picking_Web.Controllers.API
{
    public class UsuariosController : ApiController
    {

        private ApplicationDbContext _context;

        public UsuariosController()
        {
            _context = new ApplicationDbContext();
        }

        // GET /api/usuarios
        public IHttpActionResult GetUsuarios(string query = null)
        {
            List<UsuariosDto> usuariosDtos = _context.Users.ToList().Select(Mapper.Map<ApplicationUser, UsuariosDto>).ToList();

            if (User.Identity.GetUserId() != Privilegios.AdminUserID && User.Identity.GetUserId() != Privilegios.ConvidadoUserID)
            {
                var userAdmin = usuariosDtos.Find(u => u.Id == Privilegios.AdminUserID);
                var userConv = usuariosDtos.Find(u => u.Id == Privilegios.ConvidadoUserID);

                usuariosDtos.Remove(userAdmin);
                usuariosDtos.Remove(userConv);
            }

            return Ok(usuariosDtos);
        }

        // GET /api/usuarios
        public IHttpActionResult GetUsuariosSAP(int empresa_id)
        {
            try
            {
                return Ok(SAPHelper.GetUsuariosSap(_context, empresa_id));
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }


        // DELETE /api/usuarios/1
        [HttpDelete]
        public IHttpActionResult DeletarUsuario(string id)
        {
            var usuarioInDb = _context.Users.Single(u => u.Id == id);

            if (usuarioInDb == null)
            {
                return NotFound();
            }

            _context.Users.Remove(usuarioInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Picking_Web/Controllers/UsuariosController.cs
using Picking_Web.Models;
using System.Web.Mvc;

namespace Picking_Web.Controllers
{
    public class UsuariosController : MyController
    {
        private ApplicationDbContext _context;

        public UsuariosController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Usuarios
        public ActionResult Index()
        {
            SetUserIdInViewBag();
            return View();
        }

        public ActionResult Novo()
        {
            return RedirectToAction("Register", "Account");
        }

        public ActionResult Editar(string id)
        {
            return RedirectToAction("Editar", "Account", new { id = id });
        }
    }
}

Picking_Web/Views/Usuarios/Index.cshtml
@using Picking_Web.Models
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Usuários";
    Layout = "~/Views/Shared/_Administracao.cshtml";
    string ControllerName = "usuarios";
    string userid = ViewBag.userid;
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Novo Usuário","Novo","Usuarios", null, new { @class = "btn btn-primary" })
</p>
<table id="usuarios" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Ativo?</th>
        <th>Licenciado?</th>
        <th>Operador?</th>
        <th>Deletar</th>
    </tr>
    </thead>
    <tbody>
        
    </tbody>
</table>
@section scripts
{
    <script type="text/javascript">
        var DefaultApiPath = '@(Url.Action("", "api/" + ControllerName))';
        var DefaultPath = '@(Url.Action("", "" + ControllerName))';
        InitWS("@userid");
    </script>
    <script src="~/Scripts/Site/Usuarios.js"></script>
}